theme: jekyll-theme-dinky
gems: 
  - jekyll-paginate
  - jekyll-seo-tag
title: Downhill Simplex for Delphi
description: Components implementing downhill simplex algorithm for Delphi & Lazarus (Windows, Linux).
social:
  name: Dmitry Morozov
  links:
    - https://www.facebook.com/profile.php?id=100004082021870
    - https://ru.linkedin.com/pub/dmitry-morozov/59/90a/794
    - https://github.com/dvmorozov 
